### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by lawalalao** [Togodevelopers/Api_commune_Togo#1]
On peut discuter ici

**Comment by gausoft** [comment]
Allright!
Je me disais si vous avez trouvé quelques sources de données.

https://dagl.tg [District de Lomé]

Dans la section communes il y a une douzaine

**Comment by lawalalao** [comment]
On peut déjà commencer par récolter les données qu'on a . Déjà y'a pas mal d'informations sur le site du district de Lomé

**Comment by gausoft** [comment]
On organise les infos comment du coup?
Pour le moment je n'ai identifier que les noms des communes avec un descriptif de la limite de ces dernières

**Comment by lawalalao** [comment]
Tu peux cloner le repository et créer un dossier data puis des fichiers md ou pdf (Data_commune_gausoft.md ) pour mettre tout ce que tu trouves comme données.

**Comment by koffisani** [comment]
Déjà, merci à tous pour cette initiative. Je demandais quelque part les contours du projet. Je crois que l'idée derrière, même si on dispose d'un site, c'est d'avoir une source de données, éventuellement sous forme de service web par exemple, ou même de simples fichiers json.
Juste un avis.

**Comment by lawalalao** [comment]
Justement chef,il faut qu'on définisse tout ceci ensemble.

**Comment by lawalalao** [comment]
Dans le readme il ya une partie projet .. on le mettra la bas pour que tout le monde puisse savoir

**Comment by kpotia** [comment]
Voici une liste des subdivisions au Togo que je suis entrain d'utiliser en attendant 
[Subdivision du TOGO from wikipedia](https://fr.wikipedia.org/wiki/Subdivisions_du_Togo)

**Comment by manutheblacker** [comment]
Okay, @kpotia penses-tu que celà pourras nous aider?

**Comment by kpotia** [comment]
Oui c'est ce que je suis entrain d'utiliser pour le projet [Africa State](https://github.com/homescriptone/africa-states).

ca a les elements par rapports au villes, préfectures et communes dont nous avons besoins.

**Comment by lawalalao** [comment]
Okay cool

**Comment by gausoft** [comment]
@kpotia Tu peux nous en dire plus sur le projet [Africa State](https://github.com/homescriptone/africa-states) ?

**Comment by kpotia** [comment]
Le Projet Africa State est un projet pour lister les communes des pays de l'Afrique. le projet est initialiser par @manutheblacker. Il vous donnera plus de details a propos du projet.

**Comment by gausoft** [comment]
Ok, 
Et par rapport au projet globalement j'aimerais si possible qu'on en discute via un call sur Google Meet

**Comment by manutheblacker** [comment]
@Gausoft, je travaillais sur un projet pour un client où j'avais besoin des communes des différents pays d'Afrique.

Après des heures de recherches, je me suis rendu compte qu'il n'y avait pas de librairie ou outil qui permettait de l'intégrer facilement dans une application.

En gros, avec la librairie, il est plus facile de récupérer cette liste et de l'intégrer dans une application.

**Comment by gausoft** [comment]
Ok

**Comment by manutheblacker** [comment]
Que penses-tu @Gausoft, pouvez-vous aider à atteindre l'objectif qui est de pouvoir lister tous les pays d'Afrique et leurs états/communes et le faire adopter pour vos divers projets, j'ai commencé par ajouter les communes du Bénin et de la Côte d'Ivoire, le prochain est le Togo , je vais créer un roadmap pour le projet.

**Comment by lawalalao** [comment]
En gros ici l'objectif est de faire une API qui sera OS . avec celle ci on pourra récuperer la liste des villes/comunes par région , la liste des prefectures etc... 
le max d'informations possible..   Après on pourra rajouter pour les autres pays dès qu'on aura les data nécessaires

**Comment by lawalalao** [comment]
Actuellement je travaille sur l'architecture globale. je pusherai dans les jours à venir une première implémentation avec lequel vous pourrez récuperer la liste de toutes les régions/communes/ villes de Togo

**Comment by manutheblacker** [comment]
Okay super, bon travail

**Comment by gausoft** [comment]
> Ok, Et par rapport au projet globalement j'aimerais si possible qu'on en discute via un call sur Google Meet

Euuh, en fait l'idée derrière le call c'etait aussi par exemple de voir la position de chaque contributeur actu afin de ne pas dispercer notre energie à faire quelque chose que quelqu'un est entrain de faire.  
PS. Il y'a au moins une demi douzaine de contributeurs...
A répondre à certaines questions : 
* Quelles sources de données existent?
* Comment les infos seront structuées ?
* Et qu'est ce qui est pertinant ?
* Quelle techno serait utilisée pour l'api?
* Comment se fera le déploiement (Nom de domaine, hébergment)?

Mais on peut en discuter ici

**Comment by lawalalao** [comment]
STACK : JS/Typescript (node /express) ou PHP (symfony/laravel)
deploiement : on pourra utiliser heroku ou firebase mais vous pourrez toujours proposer

**Comment by manutheblacker** [comment]
Quel est votre disponibilité, je suis disponible jeudi après-midi et dimanche
